    # INF QcomPkg/PatchedBinaries/DisplayDxe.inf
    # INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/MsAbstractPkg/Drivers/MsAbstractLayerDxe/MsAbstractLayer.inf
    # INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/MsCommonPkg/Drivers/ColorbarsDxe/ColorbarsDxe.inf
    # INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/MsCommonPkg/Drivers/MsManufacturingModeDxe/MsManufacturingMode.inf
    # INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/MsCommonPkg/Drivers/SurfaceTouchHidDxe/SurfaceTouchHidDxeV2.inf
    # INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Application/QcomChargerApp/QcomChargerApp.inf
    # INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/ASN1X509Dxe/ASN1X509Dxe.inf
    # INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/ClockDxe/ClockDxe.inf
    # INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/CPRDxe/CPRDxe.inf
    # INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/DisplayDxe/DisplayDxe.inf
    # INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/EnvDxe/EnvDxe.inf
    # INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/FeatureEnablerDxe/FeatureEnablerDxe.inf
    # INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/MinidumpTADxe/MinidumpTADxe.inf
    # INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/PmicDxe/PmicDxeLa.inf
    # INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/QcomBds/QcomBds.inf
    # INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/QcomWDogDxe/QcomWDogDxe.inf
    # INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/RNGDxe/RngDxe.inf
    # INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/SecRSADxe/SecRSADxe.inf
    # INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/TzDxe/ScmDxeLA.inf
    # INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/TzDxe/TzDxeLA.inf
    # INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/UCDxe/UCDxe.inf
    # INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/UFSDxe/UFSDxe.inf
    # INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/UsbBusDxe/UsbBusDxe.inf
    # INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/UsbConfigDxe/UsbConfigDxe.inf
    # INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/UsbKbDxe/UsbKbDxe.inf
    # INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/UsbMassStorageDxe/UsbMassStorageDxe.inf
    # INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/VariableDxe/VariableDxe.inf
    # INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/VerifiedBootDxe/VerifiedBootDxe.inf
    # INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/XhciDxe/XhciDxe.inf
    # INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/Sm8350FamilyPkg/Drivers/UfsSecurityDxe/UfsSecurityDxe.inf
    INF MdeModulePkg/Universal/Disk/PartitionDxe/PartitionDxe.inf
    INF QcomPkg/PatchedBinaries/ClockDxe.inf
    INF QcomPkg/PatchedBinaries/MinidumpTADxe.inf
    INF QcomPkg/PatchedBinaries/MsAbstractLayer.inf
    INF QcomPkg/PatchedBinaries/MsManufacturingMode.inf
    INF QcomPkg/PatchedBinaries/PmicDxeLa.inf
    INF QcomPkg/PatchedBinaries/QcomWDogDxe.inf
    INF QcomPkg/PatchedBinaries/SurfaceTouchHidDxeV2.inf
    INF QcomPkg/PatchedBinaries/UFSDxe.inf
    INF QcomPkg/PatchedBinaries/UsbConfigDxe.inf
    INF SurfaceDuoFamilyPkg/Driver/GpioButtons/GpioButtons.inf
    INF SurfaceDuoFamilyPkg/Driver/SimpleFbDxe/SimpleFbDxe.inf
    INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/MsCommonPkg/Drivers/MsEnvDxe/MsEnvDxe.inf
    INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/MsCommonPkg/Drivers/MsTouchPointDxe/MsTouchPoint.inf
    INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/MsCommonPkg/Drivers/TouchControllerInitDxe/TouchControllerInitDxe.inf
    INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/MsCommonPkg/Drivers/TouchUtilsDxe/TouchUtilsDxe.inf
    INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/ButtonsDxe/ButtonsDxe.inf
    INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/ChargerExDxe/ChargerExDxe.inf
    INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/ChipInfoDxe/ChipInfoDxe.inf
    INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/CmdDbDxe/CmdDbDxe.inf
    INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/DALSYSDxe/DALSYSDxe.inf
    INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/DDRInfoDxe/DDRInfoDxe.inf
    INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/EmbeddedMonotonicCounter/EmbeddedMonotonicCounter.inf
    INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/FontDxe/FontDxe.inf
    INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/FvUtilsDxe/FvUtilsDxe.inf
    INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/GLinkDxe/GLinkDxe.inf
    INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/GpiDxe/GpiDxe.inf
    INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/HALIOMMUDxe/HALIOMMUDxe.inf
    INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/HWIODxe/HWIODxe.inf
    INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/I2CDxe/I2CDxe.inf
    INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/ICBDxe/ICBDxe.inf
    INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/IPCCDxe/IPCCDxe.inf
    INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/NpaDxe/NpaDxe.inf
    INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/ParserDxe/ParserDxe.inf
    INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/PILDxe/PILDxe.inf
    INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/PILProxyDxe/PILProxyDxe.inf
    INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/PlatformInfoDxe/PlatformInfoDxe.inf
    INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/PmicGlinkDxe/PmicGlinkDxe.inf
    INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/PwrUtilsDxe/PwrUtilsDxe.inf
    INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/QcomChargerDxe/QcomChargerDxeLA.inf
    INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/ResetRuntimeDxe/ResetRuntimeDxe.inf
    INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/RpmhDxe/RpmhDxe.inf
    INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/SdccDxe/SdccDxe.inf
    INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/SerialPortDxe/SerialPortDxe.inf
    INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/ShmBridgeDxe/ShmBridgeDxeLA.inf
    INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/SimpleTextInOutSerialDxe/SimpleTextInOutSerial.inf
    INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/SmemDxe/SmemDxe.inf
    INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/SPIDxe/SPIDxe.inf
    INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/SPMIDxe/SPMIDxe.inf
    INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/SPSSDxe/SPSSDxe.inf
    INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/TLMMDxe/TLMMDxe.inf
    INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/TsensDxe/TsensDxe.inf
    INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/ULogDxe/ULogDxe.inf
    INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/UsbDeviceDxe/UsbDeviceDxe.inf
    INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/UsbfnDwc3Dxe/UsbfnDwc3Dxe.inf
    INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/UsbInitDxe/UsbInitDxe.inf
    INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/UsbMsdDxe/UsbMsdDxe.inf
    INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/UsbPwrCtrlDxe/UsbPwrCtrlDxe.inf
    INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/VcsDxe/VcsDxe.inf
    INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/XhciPciEmulationDxe/XhciPciEmulationDxe.inf
    INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/Sm8350FamilyPkg/Drivers/ExtFgDxe/ExtFgDxe.inf
    INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/Sm8350FamilyPkg/Drivers/MsDebugDxe/MsDebugDxe.inf
    INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/Sm8350FamilyPkg/Drivers/MsDfciDxe/MsDfciDxe.inf
    INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/Sm8350FamilyPkg/Drivers/MsFRUDxe/MsFRUDxe.inf
    INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/Sm8350FamilyPkg/Drivers/MsXblHlosHobDxe/MsXblHlosHobDxe.inf
    INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/Sm8350FamilyPkg/Drivers/SfpdUtils/SfpdUtils.inf
    INF Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/Sm8350FamilyPkg/Drivers/TimestampDxe/TimestampDxe.inf

    FILE DRIVER = 4b4973ee-401b-4f36-a6a9-533dfccdfc33 {
            SECTION PE32 = Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/TzDxe/ScmDxeLA.efi
            SECTION UI = "ScmDxeLA"
    }

    FILE DRIVER = cf6dfc66-14ab-4e13-84db-9c02912d1404 {
            SECTION PE32 = Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/TzDxe/TzDxeLA.efi
            SECTION UI = "TzDxeLA"
    }

    FILE DRIVER = 6b38f7b4-ad98-40e9-9093-aca2b5a253c4 {
            SECTION PE32 = Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/MdeModulePkg/Universal/Disk/DiskIoDxe/DiskIoDxe.efi
            SECTION UI = "DiskIoDxe"
    }

    FILE DRIVER = 1c04f529-0612-4319-9315-b2e75c16810a {
            SECTION PE32 = QcomPkg/PatchedBinaries/FeatureEnablerDxe.efi
            SECTION UI = "FeatureEnablerDxe"
    }

    FILE DRIVER = b7f50e91-a759-412c-ade4-dcd03e7f7c28 {
            SECTION PE32 = Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/XhciDxe/XhciDxe.efi
            SECTION UI = "XhciDxe"
    }

    FILE DRIVER = 240612b7-a063-11d4-9a3a-0090273fc14d {
            SECTION PE32 = Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/UsbBusDxe/UsbBusDxe.efi
            SECTION UI = "UsbBusDxe"
    }

    FILE DRIVER = 2d2e62cf-9ecf-43b7-8219-94e7fc713dfe {
            SECTION PE32 = Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/UsbKbDxe/UsbKbDxe.efi
            SECTION UI = "UsbKbDxe"
    }

    FILE DRIVER = 9fb4b4a7-42c0-4bcd-8540-9bcc6711f83e {
            SECTION PE32 = Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/UsbMassStorageDxe/UsbMassStorageDxe.efi
            SECTION UI = "UsbMassStorageDxe"
    }

    FILE DRIVER = 5f0937cd-73f9-445e-b320-bb6fd5d3cbde {
            SECTION PE32 = Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/UCDxe/UCDxe.efi
            SECTION UI = "UCDxe"
    }

    FILE DRIVER = b0d3689e-11f8-43c6-8ece-023a29cec35b {
            SECTION PE32 = Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Drivers/RNGDxe/RngDxe.efi
            SECTION UI = "RngDxe"
    }

    FILE APPLICATION = eee9c2b1-16ca-4f34-87ea-2e6d1e160cc4 {
            SECTION UI = "QcomChargerApp"
            SECTION PE32 = Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/QcomPkg/Application/QcomChargerApp/QcomChargerApp.efi
    }

    FILE FREEFORM = A91D838E-A5FA-4138-825D-455E23030794 {
        SECTION UI = "logo1.bmp"
        SECTION RAW = Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/RawFiles/logo1.bmp
    }

    FILE FREEFORM = 5D3485F0-3C38-4B8B-B1EF-D5D7057708D2 {
        SECTION UI = "uilogo.bmp"
        SECTION RAW = Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/RawFiles/uilogo.bmp
    }

    FILE FREEFORM = 8CAE2C55-FC5A-410B-812B-8CA22F572F36 {
        SECTION UI = "Panel_truly_wqxga_dsc_cmd.xml"
        SECTION RAW = Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/RawFiles/Panel_truly_wqxga_dsc_cmd.xml
    }

    FILE FREEFORM = 13AC9DC9-0092-4374-AE1A-06FF35950FD0 {
        SECTION UI = "Panel_truly_wqxga_dsc_vid.xml"
        SECTION RAW = Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/RawFiles/Panel_truly_wqxga_dsc_vid.xml
    }

    FILE FREEFORM = FC6315F9-F8FE-4222-A1E3-226DF55D7592 {
        SECTION UI = "Panel_truly_wqxga_dual_cmd.xml"
        SECTION RAW = Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/RawFiles/Panel_truly_wqxga_dual_cmd.xml
    }

    FILE FREEFORM = 95E7B040-26A2-4511-9ABB-1D95D6DA7082 {
        SECTION UI = "Panel_truly_wqxga_dual_vid.xml"
        SECTION RAW = Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/RawFiles/Panel_truly_wqxga_dual_vid.xml
    }

    FILE FREEFORM = 8BC595B7-391A-4A9A-8256-5B9983B30392 {
        SECTION UI = "Panel_sharp_4k_dsc_cmd.xml"
        SECTION RAW = Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/RawFiles/Panel_sharp_4k_dsc_cmd.xml
    }

    FILE FREEFORM = 19B58ACD-B1F8-4078-B9A5-A33584B680E2 {
        SECTION UI = "Panel_sharp_4k_dsc_vid.xml"
        SECTION RAW = Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/RawFiles/Panel_sharp_4k_dsc_vid.xml
    }

    FILE FREEFORM = 0AE323D6-2EBE-11E8-8349-9BA636A0D80C {
        SECTION UI = "Panel_sharp_1080p_cmd.xml"
        SECTION RAW = Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/RawFiles/Panel_sharp_1080p_cmd.xml
    }

    FILE FREEFORM = 87273B42-311D-11E8-9324-DFB2DADFC3D1 {
        SECTION UI = "Panel_truly_1080p_cmd.xml"
        SECTION RAW = Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/RawFiles/Panel_truly_1080p_cmd.xml
    }

    FILE FREEFORM = BAFD3200-311D-11E8-8651-0FB3CACF38FB {
        SECTION UI = "Panel_truly_1080p_vid.xml"
        SECTION RAW = Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/RawFiles/Panel_truly_1080p_vid.xml
    }

    FILE FREEFORM = 88CA5ABF-D0AC-4093-A68C-0CFAE1EF9635 {
        SECTION UI = "Panel_boe_amoled_wqhd_dsc_cmd.xml"
        SECTION RAW = Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/RawFiles/Panel_boe_amoled_wqhd_dsc_cmd.xml
    }

    FILE FREEFORM = 6523A5C9-91CB-45C0-A2DC-25997CF23369 {
        SECTION UI = "Panel_boe_amoled_wqhd_dsc_vid.xml"
        SECTION RAW = Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/RawFiles/Panel_boe_amoled_wqhd_dsc_vid.xml
    }

    FILE FREEFORM = D7170685-5965-4B44-9305-37CDB199B9BE {
        SECTION UI = "Panel_boe_amoled_fhd_dsc_cmd.xml"
        SECTION RAW = Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/RawFiles/Panel_boe_amoled_fhd_dsc_cmd.xml
    }

    FILE FREEFORM = 8F276EE4-E75E-4C3B-8BCC-C37771E26478 {
        SECTION UI = "Panel_nt36860_wqhd_dsc_cmd.xml"
        SECTION RAW = Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/RawFiles/Panel_nt36860_wqhd_dsc_cmd.xml
    }

    FILE FREEFORM = 6F2D4884-D8A0-11E9-AF7A-D77B1FE990EC {
        SECTION UI = "Panel_nt36860_wqhd_dsc_vid.xml"
        SECTION RAW = Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/RawFiles/Panel_nt36860_wqhd_dsc_vid.xml
    }

    FILE FREEFORM = 81CE7295-491D-4E3F-AAA7-AB43FEF2F615 {
        SECTION UI = "Panel_r66451_60hz_fhd_plus_dsc_cmd.xml"
        SECTION RAW = Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/RawFiles/Panel_r66451_60hz_fhd_plus_dsc_cmd.xml
    }

    FILE FREEFORM = 81CE7295-491D-4E3F-AAA7-AB43FEF2F692 {
        SECTION UI = "Panel_r66451_fhd_plus_60hz_dsc_cmd.xml"
        SECTION RAW = Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/RawFiles/Panel_r66451_fhd_plus_60hz_dsc_cmd.xml
    }

    FILE FREEFORM = 8297C793-9861-422C-9F67-D447AF1EA812 {
        SECTION UI = "Panel_r66451_120hz_fhd_plus_dsc_cmd.xml"
        SECTION RAW = Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/RawFiles/Panel_r66451_120hz_fhd_plus_dsc_cmd.xml
    }

    FILE FREEFORM = 61156380-EB8A-4618-940F-AB9BDEA1EEC2 {
        SECTION UI = "Panel_r66451_120hz_fhd_plus_dsc_cmd_hdk.xml"
        SECTION RAW = Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/RawFiles/Panel_r66451_120hz_fhd_plus_dsc_cmd_hdk.xml
    }

    FILE FREEFORM = 44B09226-C2B4-45ED-AA6F-6686DB103978 {
        SECTION UI = "Panel_r66451_120hz_fhd_plus_dsc_vid.xml"
        SECTION RAW = Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/RawFiles/Panel_r66451_120hz_fhd_plus_dsc_vid.xml
    }

    FILE FREEFORM = D3F8580C-CCB8-4804-BB03-776E7B542FC2 {
        SECTION UI = "Panel_secondary_truly_1080p_cmd.xml"
        SECTION RAW = Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/RawFiles/Panel_secondary_truly_1080p_cmd.xml
    }

    FILE FREEFORM = D192FEE9-6A04-4BE8-ABFE-5534E2B457EC {
        SECTION UI = "Panel_secondary_truly_1080p_vid.xml"
        SECTION RAW = Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/RawFiles/Panel_secondary_truly_1080p_vid.xml
    }

    FILE FREEFORM = 13594E78-635E-49C9-80C7-F2A3EF8D959B {
        SECTION UI = "Panel_r66451_60hz_fhd_plus_dsc_cmd_cphy.xml"
        SECTION RAW = Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/RawFiles/Panel_r66451_60hz_fhd_plus_dsc_cmd_cphy.xml
    }

    FILE FREEFORM = 40C19F7E-C171-4C05-9C56-DE6E30AED8C9 {
        SECTION UI = "Panel_r66451_90hz_fhd_plus_dsc_vid_cphy.xml"
        SECTION RAW = Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/RawFiles/Panel_r66451_90hz_fhd_plus_dsc_vid_cphy.xml
    }

    FILE FREEFORM = 7246C37A-04E7-4D15-8DB6-638D8B59155E {
        SECTION UI = "Surface_Elgin_Panel_cmd_dsc_dsi0.xml"
        SECTION RAW = Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/RawFiles/Surface_Elgin_Panel_cmd_dsc_dsi0.xml
    }

    FILE FREEFORM = 8CA934CC-4385-4D4E-BC8B-37E8AC0B0960 {
        SECTION UI = "Surface_Elgin_Panel_cmd_dsc_dsi1.xml"
        SECTION RAW = Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/RawFiles/Surface_Elgin_Panel_cmd_dsc_dsi1.xml
    }

    FILE FREEFORM = 4365FDD2-2A06-11EB-ADC1-0242AC120002 {
        SECTION UI = "Surface_Elgin_Panel_cmd_dsc_dsi0_ev2.xml"
        SECTION RAW = Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/RawFiles/Surface_Elgin_Panel_cmd_dsc_dsi0_ev2.xml
    }

    FILE FREEFORM = 54DE8CDC-2A06-11EB-ADC1-0242AC120002 {
        SECTION UI = "Surface_Elgin_Panel_cmd_dsc_dsi1_ev2.xml"
        SECTION RAW = Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/RawFiles/Surface_Elgin_Panel_cmd_dsc_dsi1_ev2.xml
    }

    FILE FREEFORM = EDC40719-989A-45D4-9442-1E35AF98D8A6 {
        SECTION UI = "Surface_Elgin_Panel_cmd_dsc_dsi0_ev3.xml"
        SECTION RAW = Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/RawFiles/Surface_Elgin_Panel_cmd_dsc_dsi0_ev3.xml
    }

    FILE FREEFORM = D0EEC6E6-EE21-438A-A7FB-8252F1F0F25D {
        SECTION UI = "Surface_Elgin_Panel_cmd_dsc_dsi1_ev3.xml"
        SECTION RAW = Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/RawFiles/Surface_Elgin_Panel_cmd_dsc_dsi1_ev3.xml
    }

    FILE FREEFORM = BA2F91C8-278E-447E-9121-373B0D812651 {
        SECTION UI = "Surface_Elgin_Panel_cmd_dsc_dsi0_dv.xml"
        SECTION RAW = Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/RawFiles/Surface_Elgin_Panel_cmd_dsc_dsi0_dv.xml
    }

    FILE FREEFORM = B374F91E-464C-4325-9F9B-657035B9A9B6 {
        SECTION UI = "Surface_Elgin_Panel_cmd_dsc_dsi1_dv.xml"
        SECTION RAW = Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/RawFiles/Surface_Elgin_Panel_cmd_dsc_dsi1_dv.xml
    }

    FILE FREEFORM = A21F6348-4F65-4BF0-BCDD-B8DE64D9AB5A {
        SECTION UI = "Surface_Elgin_Panel_cmd_dsc_dsi0_mp.xml"
        SECTION RAW = Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/RawFiles/Surface_Elgin_Panel_cmd_dsc_dsi0_mp.xml
    }

    FILE FREEFORM = 84267C04-7399-498B-B294-0CEB2B369169 {
        SECTION UI = "Surface_Elgin_Panel_cmd_dsc_dsi1_mp.xml"
        SECTION RAW = Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/RawFiles/Surface_Elgin_Panel_cmd_dsc_dsi1_mp.xml
    }

    FILE FREEFORM = C32CB97A-D116-4D64-83B9-6BA1236057AD {
        SECTION UI = "Panel_boe_amoled_wqhd_dsc_cmd_demura.xml"
        SECTION RAW = Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/RawFiles/Panel_boe_amoled_wqhd_dsc_cmd_demura.xml
    }

    FILE FREEFORM = 453D4CEB-2EC9-49A6-8EEC-B233EB679591 {
        SECTION UI = "Panel_boe_amoled_wqhd_dsc_vid_demura.xml"
        SECTION RAW = Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/RawFiles/Panel_boe_amoled_wqhd_dsc_vid_demura.xml
    }

    FILE FREEFORM = 602CFFCD-8A5E-438E-B432-BF1A656A2561 {
        SECTION UI = "Panel_secondary_r66451_fhd_plus_dsc_cmd.xml"
        SECTION RAW = Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/RawFiles/Panel_secondary_r66451_fhd_plus_dsc_cmd.xml
    }

    FILE FREEFORM = 21E9BDD9-6C3F-4F10-84A5-BBEC322741F1 {
        SECTION UI = "uefipil.cfg"
        SECTION RAW = Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/RawFiles/uefipil.cfg
    }

    FILE FREEFORM = 45FE4B7C-150C-45DA-A021-4BEB2048EC6F {
        SECTION UI = "QcomChargerCfg.cfg"
        SECTION RAW = Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/RawFiles/QcomChargerCfg.cfg
    }

    FILE FREEFORM = F780C779-DD7C-47CD-BD1A-5EB414C51704 {
        SECTION UI = "BATTERY.PROVISION"
        SECTION RAW = Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/RawFiles/BATTERY.PROVISION
    }

    FILE FREEFORM = A91D838E-A5FA-4138-825D-455E2303079E {
        SECTION UI = "BDS_Menu.cfg"
        SECTION RAW = Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/RawFiles/BDS_Menu.cfg
    }

    FILE FREEFORM = A1E235DE-E825-4591-9623-C43175811826 {
        SECTION UI = "SecParti.cfg"
        SECTION RAW = Zeta/BOOT.MXF.1.0-00893-LAHAINA-1.7786.2/RawFiles/SecParti.cfg
    }